# size in KB

[MicroBench]

ReadFileSize	= 131072 ;
WriteFileSize	= 2048 ;
SeqBufferSize = 256 ;
RndBufferSize = 4 ;
RndSeed				= 0 ;

[Postermark]

NumDirs				= 2 ;
NumFiles			= 250 ;
NumTrans			= 100 ;
FileSizeMin		= 4 ;
FileSizeMax		= 256 ;
BufferSize		= 4 ;
